-- =============================================================
-- Outstanding migrations, combined into one paste.
--
-- Contents, in order: 0041 plan coupons, 0042 Tomora Live,
-- 0044 direct settlement, 0045 creator subaccounts.
-- 0043 is already applied and is not repeated here.
--
-- RUN supabase/apply-outstanding-step1.sql FIRST. It is a single
-- ALTER TYPE ... ADD VALUE, which Postgres will not accept inside
-- a transaction block. The SQL editor wraps a pasted file in one
-- transaction, so leaving it here would roll back everything.
--
-- Safe to run more than once. Every statement is guarded with
-- `if not exists` or `or replace`, so re-running changes nothing.
-- If any part fails, none of it is applied.
--
-- Generated from supabase/migrations. Do not edit this file.
-- =============================================================



-- >>>>>>>>>>>>>>>> 0041_plan_coupons.sql

-- =============================================================
-- Subscription coupon codes.
--
-- `plan_discounts` (0009) is a blanket price cut everyone sees on the pricing
-- page. This is the opposite: a code only the people you give it to can use,
-- redeemed at subscription or renewal checkout.
--
-- RLS deny-all; all access goes through the service-role client in server code.
-- =============================================================

create extension if not exists "pgcrypto";

create table if not exists public.plan_coupons (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,                        -- stored uppercase
  percent integer not null default 0,               -- 1..100 off the plan price
  plan_id text,                                     -- null = valid on any plan
  max_uses integer,                                 -- null = unlimited
  used_count integer not null default 0,
  per_user_limit integer default 1,                 -- null = unlimited per user
  active boolean not null default true,
  expires_at timestamptz,                           -- null = never expires
  note text,                                        -- what it is for, admin eyes only
  created_at timestamptz not null default now()
);
create index if not exists plan_coupons_code_idx on public.plan_coupons(code);

-- One row per successful redemption. Doubles as the per-user cap and the
-- audit trail of who used what, keyed by the payment it paid for.
create table if not exists public.plan_coupon_redemptions (
  id uuid primary key default gen_random_uuid(),
  coupon_id uuid not null references public.plan_coupons(id) on delete cascade,
  user_id uuid not null,
  reference text unique not null,                   -- the Paystack reference
  plan_id text,
  percent integer not null default 0,
  discount_amount integer not null default 0,       -- naira taken off
  created_at timestamptz not null default now()
);
create index if not exists plan_coupon_redemptions_coupon_idx on public.plan_coupon_redemptions(coupon_id);
create index if not exists plan_coupon_redemptions_user_idx on public.plan_coupon_redemptions(user_id);

alter table public.plan_coupons enable row level security;
alter table public.plan_coupon_redemptions enable row level security;
-- No policies: deny-all.

-- Atomic increment. Two people redeeming the last use of a code at the same
-- moment would both pass a read-then-write check; a single UPDATE cannot.
create or replace function public.bump_plan_coupon_use(p_coupon uuid)
returns integer
language sql
security definer
set search_path = public
as $$
  update public.plan_coupons
     set used_count = used_count + 1
   where id = p_coupon
  returning used_count;
$$;


-- >>>>>>>>>>>>>>>> 0042_tomora_live.sql

-- =============================================================
-- Tomora Live: the store, inside WhatsApp.
--
-- Deliberately additive. Products, sites, profiles, wallets and the ledger are
-- reused exactly as they are; an order placed in WhatsApp writes the same order
-- rows a website order does, so it appears in the seller's existing dashboard
-- with no changes there.
--
-- RLS deny-all; all access goes through the service-role client in server code.
-- =============================================================

create extension if not exists "pgcrypto";

-- The seller's Live presence. One per site.
--
-- Customers all message one shared Tomora number, so the routing key is the
-- store_code the customer arrives with (wa.me/<number>?text=SHOP%20ADEBAYO),
-- not the phone number they messaged. phone_number_id is recorded anyway so
-- that moving a seller onto their own number later is a data change, not a
-- rewrite.
create table if not exists public.live_accounts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  site_id uuid not null references public.sites(id) on delete cascade unique,
  store_code text not null unique,                  -- uppercase, what customers type
  phone_number_id text,                             -- set only when on a dedicated number
  waba_id text,
  display_phone text,
  status text not null default 'active',            -- active | paused
  greeting text,                                    -- overrides the default welcome
  activated_at timestamptz not null default now()
);
create index if not exists live_accounts_user_idx on public.live_accounts(user_id);
create index if not exists live_accounts_code_idx on public.live_accounts(store_code);

-- One row per customer conversation. `state` holds the current screen and the
-- cart: the cart lives here on the server, never in a message the customer
-- could edit and send back.
create table if not exists public.live_conversations (
  id uuid primary key default gen_random_uuid(),
  live_account_id uuid references public.live_accounts(id) on delete cascade,
  customer_wa_id text not null,                     -- the customer's phone, E.164 digits
  state jsonb not null default '{}'::jsonb,
  last_message_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (customer_wa_id)
);
create index if not exists live_conversations_account_idx on public.live_conversations(live_account_id);

-- Inbound and outbound message log. wa_message_id is unique so a webhook
-- redelivery is recognised and ignored rather than replayed.
create table if not exists public.live_messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid references public.live_conversations(id) on delete cascade,
  wa_message_id text unique,
  direction text not null,                          -- in | out
  payload jsonb,
  created_at timestamptz not null default now()
);
create index if not exists live_messages_conversation_idx on public.live_messages(conversation_id);

-- Outbound queue. Vercel has no worker, so a cron route drains this: a status
-- message that fails to send retries instead of vanishing.
create table if not exists public.live_outbox (
  id uuid primary key default gen_random_uuid(),
  to_wa_id text not null,
  payload jsonb not null,
  -- An order is stored as one row per line item, so marking a 3-item order
  -- shipped calls the update three times. A unique key like
  -- "tomwa_123:shipped" is what stops the customer getting three messages.
  dedupe_key text unique,
  attempts integer not null default 0,
  send_after timestamptz not null default now(),
  sent_at timestamptz,
  last_error text,
  created_at timestamptz not null default now()
);
create index if not exists live_outbox_pending_idx on public.live_outbox(sent_at, send_after);

alter table public.live_accounts enable row level security;
alter table public.live_conversations enable row level security;
alter table public.live_messages enable row level security;
alter table public.live_outbox enable row level security;
-- No policies: deny-all.

-- ---------- extensions to existing tables ----------

-- Where the order came from, so the dashboard can label it and Live's
-- commission only ever applies to Live's own sales.
alter table public.orders add column if not exists channel text not null default 'web';
alter table public.orders add column if not exists live_conversation_id uuid;

-- The seller's fulfilment flow needs a step between paid and shipped.
--
-- Run this on its own, not as part of a larger batch. Postgres restricts
-- ALTER TYPE ... ADD VALUE inside a transaction block, and a SQL editor that
-- wraps a whole pasted file in one transaction will reject it and roll back
-- everything above it. `if not exists` makes re-running it a no-op.


-- >>>>>>>>>>>>>>>> 0044_direct_settlement.sql

-- =============================================================
-- Mark payments that settle straight to the seller's own bank.
--
-- Store sales and donations paid by card now split at Paystack to the payout
-- account the owner connected, so the money never passes through Tomora. The
-- wallet still records the income, because owners read their history there,
-- but it must not be withdrawable: Tomora does not hold it, and paying it out
-- would mean paying it twice.
--
-- Rows written before this keep `false`, which is correct: that money really
-- did land in Tomora's balance and is still theirs to withdraw.
-- =============================================================

alter table public.orders
  add column if not exists settled_direct boolean not null default false;

alter table public.donations
  add column if not exists settled_direct boolean not null default false;


-- >>>>>>>>>>>>>>>> 0045_creator_subaccounts.sql

-- =============================================================
-- Creators are paid directly, like every other seller on Tomora.
--
-- A course sale used to land whole in Tomora's Paystack balance and then be
-- divided in the wallet ledger, so a creator's money sat with Tomora until
-- they asked for it. It now splits at Paystack to their own account, with
-- Tomora's 3% taken as a per-transaction charge.
--
-- Existing wallet balances stay exactly as they are and remain withdrawable:
-- that money really is in Tomora's balance and still owed.
-- =============================================================

alter table public.academy_creators
  add column if not exists paystack_subaccount text;
